--- 
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  name: oai-upf-dev
spec: 
  output: 
    to: 
      kind: ImageStreamTag
      name: "oai-upf-dev:oai-oc"
  runPolicy: Serial
  strategy:
    type: Docker
  source: 
    secrets: 
      - destinationDir: etc-pki-entitlement
        secret: 
          name: etc-pki-entitlement
    configMaps: 
      - configMap: 
          name: rhsm-conf
        destinationDir: rhsm-conf
      - configMap: 
          name: rhsm-ca
        destinationDir: rhsm-ca
    dockerfile: |
        ################################################################
        # Builder Image (can also be used as developer's image)
        ################################################################
        FROM image-registry.openshift-image-registry.svc:5000/oai4g/oai-upf-base-builder:oai-oc as oai-upf-builder
        ENV TZ=Europe/Paris
          
        WORKDIR /
        RUN git clone -b develop https://github.com/lionelgo/openair-spgwu-tiny.git
        
        WORKDIR /oai-upf/build/ext
        RUN ln -s /spdlog /oai-upf/build/ext/spdlog \
            && ln -s /json /oai-upf/build/ext/json
        WORKDIR /oai-upf/build/scripts
        RUN ./build_spgwu --clean --build-type Release --jobs --Verbose \
            && ldd /oai-upf/build/upf/build/spgwu \
            && mv /oai-upf/build/upf/build/spgwu \
                  /oai-upf/build/upf/build/oai_upf \
            && mkdir /oai-upf/bin \
            && cp /oai-upf/build/upf/build/oai_upf \
                  /oai-upf/scripts/entrypoint.sh \
                  /oai-upf/bin 


        RUN ldconfig && \
          ldd /oai-upf/bin/oai_upf
      
        WORKDIR /openair-spgwu-tiny
      
        # expose ports
        EXPOSE 2152/udp 8805/udp
      
        CMD ["/oai-upf/bin/oai_upf", "-c", "/oai-upf/etc/upf.conf", "-o"]
        ENTRYPOINT ["/oai-upf/bin/entrypoint.sh"]
      